### ISSUE TITLE
Add discussions!

### ISSUE THREAD

**Issue by pikachub2005** [webdev03/scratchinfo#1]
Not everything someone wants to say will be an issue.

**Comment by pikachub2005** [comment]
Also I've been working on https://scratchplus.am4.uk so it's kinda annoying that other people are making these sites with the api

**Comment by webdev03** [comment]
> Also I've been working on https://scratchplus.am4.uk so it's kinda annoying that other people are making these sites with the api

Sorry about that. Also I am a bit new to issues and pull requests.

**Comment by webdev03** [comment]
No problem

**Comment by pikachub2005** [comment]
I only added forum leaderboards to my site... hmm I know what I'm doing tomorrow

**Comment by webdev03** [comment]
Well, that's fine. You can add leaderboards, other sites have made my leaderboard before
