### ISSUE TITLE
BUG: "undefined" results

### ISSUE THREAD

**Issue by webdev03** [webdev03/scratchinfo#25]
**Describe the bug**
This bug shows `undefined` when you access a user who doesn't have statistics saved in ScratchDB.

**To Reproduce**
1. Go to [TWTG93](https://scratchinfo.vercel.app/users/TWTG93/)'s profile or someone who doesn't have statistics in ScratchDB
3. Scroll down to the part where followers and view statistics are shown

**Expected behavior**
All results to show or not be `undefined`

**Screenshots**
![image](https://user-images.githubusercontent.com/75148774/141593285-45f10210-8f10-4a1d-8e0e-3b487e6aefc0.png)

This happens on Playstation and on macOS 11. It is a problem with the code so we should be able to reproduce the error on every platform.

**Additional context**
This error was found from [this scratch forum post](https://scratch.mit.edu/discuss/post/5777435/).

**Comment by webdev03** [comment]
I've fixed this bug in https://github.com/webdev03/scratchinfo/commit/02bc4dccbfa3ac59a67b855a9f53525203f64d99 so I think this should be closed, I'm going to wait a bit to see if it is resolved.

**Comment by kccuber-scratch** [comment]
![image](https://user-images.githubusercontent.com/92891642/141599025-058498bd-54a2-4eb6-8760-e9e2a3934d49.png)
Huh.

**Comment by webdev03** [comment]
> ![image](https://user-images.githubusercontent.com/92891642/141599025-058498bd-54a2-4eb6-8760-e9e2a3934d49.png) Huh.
> 
> EDIT: Ok I think the issue here is that ScratchDB only indexes users with >10 followers.

I didn't see your post until just now sorry.
The fix in that commit was just to add that text you have noticed instead.

**Comment by SevenworksGD** [comment]
TWTG here. Im guessing that least popular users cannot get their stats viewed. (more popular users is fine)

**Comment by webdev03** [comment]
> TWTG here. Im guessing that least popular users cannot get their stats viewed. (more popular users is fine)

Yep, it's because the ScratchDB indexer only indexes users who have more than 10 followers I think.
