### ISSUE TITLE
Authentication system not working

### ISSUE THREAD

**Issue by JoshAtticus** [webdev03/scratchinfo#32]
**Describe the bug**
Authentication system not working

**Expected behavior**
The authentication system should log me in to you page.
**Screenshots**
N/A (screenshot tool too slow to capture the error)

**Desktop (please complete the following information):**
 - OS: Windows 11 Home OS Build 22000.318
 - Browser Firefox Nightly
 - Version 96.0a1

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 15.2 Developer Preview
 - Browser Safari
 - Version 15.2

**Additional context**
Happens on all browsers while using some wifi networks. (Networks Tried: School(Problems) Home(fine) Friend's WiFi(problems) Shopping Centre(fine))

**Comment by webdev03** [comment]
Hmm, is Fluffyscratch blocked? Maybe try to use ocular.

**Comment by webdev03** [comment]
@JoshAtticus do you think that you can turn on the "Persist Logs" button in the Firefox Network tab (the settings cog on the right > Persist Logs) and see what is going on?

**Comment by JoshAtticus** [comment]
> 
> 
> @JoshAtticus do you think that you can turn on the "Persist Logs" button in the Firefox Network tab (the settings cog on the right > Persist Logs) and see what is going on?

Yes, I will do that

**Comment by webdev03** [comment]
> > @JoshAtticus do you think that you can turn on the "Persist Logs" button in the Firefox Network tab (the settings cog on the right > Persist Logs) and see what is going on?
> 
> Yes, I will do that

I see you've authenticated with ScratchLight too.. does that work?

**Comment by JoshAtticus** [comment]
> 
> 
> > > @JoshAtticus do you think that you can turn on the "Persist Logs" button in the Firefox Network tab (the settings cog on the right > Persist Logs) and see what is going on?
> > 
> > 
> > Yes, I will do that
> 
> I see you've authenticated with ScratchLight too.. does that work?

ScratchLight: Working ✔️
FluffyScratch Auth: Not Working ❌

**Comment by webdev03** [comment]
What about the persist logs? Did that give any clues? I authenticated with the FluffyScratch system and it works for me.

**Comment by JoshAtticus** [comment]
> 
> 
> What about the persist logs? Did that give any clues? I authenticated with the FluffyScratch system and it works for me.

I turned on persist logs, just like you said

**Comment by webdev03** [comment]
> > What about the persist logs? Did that give any clues? I authenticated with the FluffyScratch system and it works for me.
> 
> I turned on persist logs, just like you said, it showed nothing

No 404's or anything? That's weird... if it works with ScratchLight you can use that for now.

**Comment by webdev03** [comment]
Since ScratchLight works, and has been merged, I'm closing this.
