### ISSUE TITLE
CONTRIBUTED? COME HERE!

### ISSUE THREAD

**Issue by webdev03** [webdev03/scratchinfo#39]
If you've contributed to the scratchinfo project, read this!
So, to add your contribution to the readme, post this
```@all-contributors add <GitHub username> for <contributions>```
<Github username> is your username on Github.
<contributions> is one of the contributions on the [emoji key](https://allcontributors.org/docs/en/emoji-key).

**Comment by webdev03** [comment]
@all-contributors

**Comment by webdev03** [comment]
@all-contributors add @webdev03 for projectManagement, code

**Comment by webdev03** [comment]
@all-contributors add @kccuber-scratch for bug, design

**Comment by webdev03** [comment]
@all-contributors add @kccuber-scratch for code

**Comment by JoshAtticus** [comment]
@all-contributors add @JoshAtticus for design, ideas, test

**Comment by JoshAtticus** [comment]
Yay

**Comment by webdev03** [comment]
@all-contributors add @JoshAtticus for design, ideas, userTesting

**Comment by webdev03** [comment]
@all-contributors generate
