### ISSUE TITLE
No error is shown to user when the studio ID is blank in the dashboard

### ISSUE THREAD

**Issue by Chiroyce1** [webdev03/scratchinfo#44]
**Describe the bug**
Server responds with `500 Internal Server Error`, but nothing is displayed to the user when you leave the studio ID blank in the `dashboard`.

**To Reproduce**

1. Go to the [dashboard](https://scratchinfo.vercel.app/dashboard)
2. Set the studio id to blank like this <img width="1315" alt="image" src="https://user-images.githubusercontent.com/97374054/148916757-3733dc58-f3a6-468f-9f35-aecd808d72a8.png">
3. Click on `Save changes`

**Expected behavior**
The user should be notified that the ID is invalid 

**Current behavior**
The user is not notified, and the server returns a `500` status code instead of `400`

**Screenshots**
<img width="680" alt="image" src="https://user-images.githubusercontent.com/97374054/148917073-5606b466-042d-49e5-83f7-69376900147f.png">

**Desktop:**

- OS: macOS Big Sur
- Browser: Firefox
- Version 94

**Comment by webdev03** [comment]
LOL

**Comment by webdev03** [comment]
Ok thanks github actions
I will change this

**Comment by webdev03** [comment]
Ah, I see. I was going to add in this later, actually. I'm just going to do it now since I am wasting too much time.

**Comment by Chiroyce1** [comment]
> I'm not familiar with status codes that much, what does `400` do? Invalid request?

400 means a Bad Request

**Comment by webdev03** [comment]
Oh, ok.

**Comment by Chiroyce1** [comment]
Tell me when it's live on the site - I'll then check if you fixed it...

**Comment by webdev03** [comment]
It should be live right now.

**Comment by Chiroyce1** [comment]
Yep it works!! 🎉

**Comment by webdev03** [comment]
@Chiroyce1 thanks for this, you're awesome for making this bug report! cc @all-contributors

**Comment by webdev03** [comment]
oh great all contributors nlp didnt understand

**Comment by webdev03** [comment]
@Chiroyce1 thanks for this bug report! @all-contributors add @Chiroyce1 for bug

**Comment by webdev03** [comment]
for bug, bug
