### ISSUE TITLE
Searching "null" doesnt work

### ISSUE THREAD

**Issue by Quantum-Codes** [webdev03/scratchinfo#50]
https://scratchinfo.vercel.app/users/null  --- doesn't show anything. Stuck on loading page .

**To Reproduce**

1. Go to https://scratchinfo.vercel.app/users/null
2. Wait for 10 years. Then you know it will never load lol

**Expected behavior**
"null" user exists on scratch. So I think It should load.

**Smartphone (please complete the following information):**

- Device:  Samsung tab 
- OS: Android
- Browser Chrome

**Additional context**
null (lol)

**Comment by webdev03** [comment]
Related: https://github.com/webdev03/scratchinfo/blob/main/src/routes/api/%5Buser%5D.ts

**Comment by webdev03** [comment]
Seems like ocular is saying https://my-ocular.jeffalo.net/api/user/null

**Comment by webdev03** [comment]
Here are the logs:
![image](https://user-images.githubusercontent.com/75148774/152705069-ac276da2-779c-48c4-9a22-db109aaf561b.png)

**Comment by webdev03** [comment]
Problem seems to be https://scratchdb.lefty.one/v3/forum/user/info/null

**Comment by hello-smile6** [comment]
> Problem seems to be https://scratchdb.lefty.one/v3/forum/user/info/null

I might make my own version of ScratchDB soon.

**Comment by webdev03** [comment]
Would adding an abort controller help?

**Comment by hello-smile6** [comment]
> Would adding an abort controller help?

Maybe. You could try to go through ScratchDB, but if it fails, fallback to loading the user's ScratchStats page with jsdom (if it's server-side) or on a detached DOM tree (if it's client-side). If you do it client-side and need a cors-anywhere instance, I have one you could use, by the way.

**Comment by webdev03** [comment]
jsdom doesnt work.. gives a canvas error..

**Comment by hello-smile6** [comment]
> jsdom doesnt work.. gives a canvas error..

Then do this. 
```
reqString=reqString.replaceAll("<canvas","<span");
reqString=reqString.replaceAll("</canvas>","</span>");
```
I do that kind of thing all the time.

**Comment by hello-smile6** [comment]
@webdev03 #52 #51

**Comment by Quantum-Codes** [comment]
Fallback to usual Scratch API?

**Comment by webdev03** [comment]
> Fallback to usual Scratch API?

Scratch does not return forum data

**Comment by hello-smile6** [comment]
> > Fallback to usual Scratch API?
> 
> Scratch does not return forum data

Maybe get the ScratchDB maintainer to fix it? Where's the source?

**Comment by Quantum-Codes** [comment]
> > > Fallback to usual Scratch API?
> > 
> > 
> > Scratch does not return forum data
> 
> Maybe get the ScratchDB maintainer to fix it? Where's the source?

Closed source. Contact DatOneLefty on scratch

**Comment by hello-smile6** [comment]
> > > > Fallback to usual Scratch API?
> > > 
> > > 
> > > Scratch does not return forum data
> > 
> > 
> > Maybe get the ScratchDB maintainer to fix it? Where's the source?
> 
> Closed source. Contact DatOneLefty on scratch

Well, they're a brick wall.

**Comment by hello-smile6** [comment]
> They reply once every few days. Just comment there about the problem

Okay, but they've already gone through a reply cycle.

**Comment by webdev03** [comment]
Not worth fixing?

**Comment by JoshAtticus** [comment]
> Not worth fixing? IDK

Yeah, you can't sign up as null anyways, and the owner of the null account isn't indexed by ScratchDB, so there is no point.
![image](https://user-images.githubusercontent.com/72828296/158526947-30a58481-daea-4459-83ec-1e84058dc1f9.png)
![image](https://user-images.githubusercontent.com/72828296/158526973-fee032f8-b6a1-4cbf-a8e1-38530d44a4fb.png)
![image](https://user-images.githubusercontent.com/72828296/158526992-104038e1-0848-400a-a438-e100638a1a52.png)

**Comment by hello-smile6** [comment]
@webdev03 Could you return a "This account is not active." message and avoid the problem entirely? If you had a JSON file with a list of names, you could also prepare for similar issues in the future.
