### ISSUE TITLE
Basic HTML or bug?

### ISSUE THREAD

**Issue by ILOVETOMAKESTUFF** [webdev03/scratchinfo#58]
**Describe the bug**
I was having internet issues and I reloaded the page and the CSS was apparently deactivated.

**To Reproduce**

1. Go to 'scratchinfo.varcel.app'
2. Click on the bottom of your screen:
3. 
![image](https://user-images.githubusercontent.com/97681427/155456724-e351a60e-13c7-4d46-b3f2-de4cb98ae85e.png)
3. turn your wifi off
4. go on a different tab
5. reopen scratchinfo
6. See error
7. Idk if this will work 🤔

**Expected behavior**
Proper design: 
![image](https://user-images.githubusercontent.com/97681427/155456920-13a6d1b0-b184-4f7b-8b4e-c8e8134bbf7e.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/97681427/155456534-5abd27f8-fc33-4800-8b72-ff74b07ce2fd.png)

**Desktop (please complete the following information):**

- OS: ChromeOS 
- Browser Chrome
- Version 97

**Smartphone (please complete the following information):**
none

**Additional context**

**Comment by hello-smile6** [comment]
@webdev03 Caching issue, you need to add a service worker.

**Comment by webdev03** [comment]
Hmm...

**Comment by webdev03** [comment]
Can't recreate the issue.. and @hello-smile6 I think SvelteKit has a service worker (not sure)

**Comment by JoshAtticus** [comment]
> * OS: Chromebook?
> * Browser Chrome
> * Version 97

It's **_actually_** ChromeOS

**Comment by ILOVETOMAKESTUFF** [comment]
@JoshAtticus Thanks

**Comment by hello-smile6** [comment]
> Can't recreate the issue.. and @hello-smile6 I think SvelteKit has a service worker (not sure)

Doesn't have one, use Workbox and add it to your build script so it runs after you build your code. Workbox will let your API endpoints fall through.

**Comment by webdev03** [comment]
I can add my own service worker, just add it in `src/service-worker.ts` @hello-smile6 can you please make PR for it?

**Comment by hello-smile6** [comment]
> I can add my own service worker, just add it in `src/service-worker.ts`, I just don't know what to put in there.. @hello-smile6 can you please make PR for it?

Can't be typescript, has to be .js . Let me see...

**Comment by webdev03** [comment]
Just make it .ts since sveltekit transpiles that to JS. You don't need to know TS.

**Comment by hello-smile6** [comment]
Or, you could build the service worker once you generate the static site, right before deploying it to Vercel's CDN.

**Comment by hello-smile6** [comment]
![Google](https://assets.scratch.mit.edu/092b702adf894dec97b8a7531c351335.png)

**Comment by webdev03** [comment]
> Or, you could build the service worker once you generate the static site, right before deploying it to Vercel's CDN.

How to generate one?

**Comment by hello-smile6** [comment]
> > Or, you could build the service worker once you generate the static site, right before deploying it to Vercel's CDN.
> 
> How to generate one?

`npx workbox-cli`, find the create one. Run your build first and output your service worker in the build output.
Then, after you build it, run `npx workbox-cli generateSW workbox-config.js`. Also, check out https://lets-annoy-jaydendev.9pfs.repl.co/ (Thanks for pointing out their analytics)
