### ISSUE TITLE
Weird stuff when clicking something

### ISSUE THREAD

**Issue by ILOVETOMAKESTUFF** [webdev03/scratchinfo#60]
**Describe the bug**
Whenever you press something anywhere (like a button) there is (a cool?) animation on the bottom-right corner.

**To Reproduce**

1. Go to 'Scratchinfo'
2. Click on 'any buttons'
3. Step 4

**Expected behavior**
Not the animation

**Screenshots**
Files won't load to github

**Desktop (please complete the following information):**

- OS: ChromeOS
- Browser Chrome
- Version 99.14469.0

**Additional context**
None

**Comment by webdev03** [comment]
Intentional - I don't think it looks that good though so I am planning on changing it.

**Comment by webdev03** [comment]
If you have any suggestions please let me know!

**Comment by hello-smile6** [comment]
> If you have any suggestions please let me know!

`.gif` or video? (You can use [gifcap.dev](https://gifcap.dev/) for recording with a web browser)

**Comment by webdev03** [comment]
https://user-images.githubusercontent.com/75148774/161677879-45926782-5e4d-4a32-b087-0b59e633bb85.mov

**Comment by hello-smile6** [comment]
> Screen.Recording.2022-04-05.at.4.17.10.PM.mov

I agree that that would be better if it was changed. If you have a build process, maybe compile [`@material/mwc-ripple`](https://github.com/material-components/material-web) (npm) into your code and put an `<mwc-ripple>` on whatever you want to have a visible response to interaction with, or maybe load `<script type="module">import "https://npmjs.com/@material/mwc-ripple";</script>` if you're okay with a cross-origin dependency... Just a suggestion

**Comment by hello-smile6** [comment]
> **Describe the bug** Whenever you press something anywhere (like a button) there is (a cool?) animation on the bottom-right corner.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to 'Scratchinfo'
> 2. Click on 'any buttons'
> 3. Step 4
> 4. See error
> 
> **Expected behavior** Not the animation
> 
> **Screenshots** Files won't load to github
> 
> **Desktop (please complete the following information):**
> 
> * OS: ChromeOS
> * Browser Chrome
> * Version 99.14469.0
> 
> **Additional context** None

Why are you on Chrome OS 99? Chrome OS 100 has been released on stable!!!

**Comment by webdev03** [comment]
School chromebooks probably are version locked

**Comment by hello-smile6** [comment]
> School chromebooks probably are version locked

Not by default. In fact, of all things to be overly restricted by default, updates aren't.

**Comment by hello-smile6** [comment]
@webdev03 Resolved?
