### ISSUE TITLE
Find an alert() alternative that doesn't block the main thread

### ISSUE THREAD

**Issue by hello-smile6** [webdev03/scratchinfo#63]
**Is your feature request related to a problem? Please describe.**
`alert()` blocks the main thread.
**Describe the solution you'd like**
A better alternative. (I could make an `alert()` polyfill using JS modules in about 1 to 2 hours)

**Describe alternatives you've considered**
N/A

**Additional context**
Extensions can't do anything when the main thread is blocked. Consider putting alert() in a web worker. $\sqrt 0 = 0$...
$$\sqrt \frac {n} {0} = 0$$
<div align="center"><h6>Try right-clicking on the above math.</h6></div>

**Comment by webdev03** [comment]
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <msqrt>
    <mfrac>
      <mi>n</mi>
      <mn>0</mn>
    </mfrac>
  </msqrt>
  <mo>=</mo>
  <mn>0</mn>
</math>

**Comment by webdev03** [comment]
Not sure yet
